theme: jekyll-theme-architect
title: Bilkent CS353 Database Systems Project
description: Mustafa Goktan Gudukbay goktan.gudukbay@ug.bilkent.edu.tr

Yusuf Ziya Ozgul  yzozgul98@gmail.com

Musa Ege Unalan egeunalan@gmail.com

Batuhan Ozcomlekci  b.ozcomlekci@ug.bilkent.edu.tr
